# Generated by Django 4.0.3 on 2022-04-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0007_alter_subject_slug'),
        ('grade', '0004_alter_grade_room_no_alter_grade_student_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam', to='grade.grade')),
            ],
        ),
        migrations.CreateModel(
            name='SingleExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('full_marks', models.PositiveSmallIntegerField()),
                ('pass_marks', models.PositiveSmallIntegerField()),
                ('exam_room', models.CharField(max_length=256)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='exam.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject')),
            ],
        ),
    ]
