# Generated by Django 4.0.3 on 2022-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_remove_singleexam_exam_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleexam',
            name='full_marks',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='singleexam',
            name='pass_marks',
            field=models.PositiveSmallIntegerField(default=40),
        ),
    ]
