# Generated by Django 4.0.3 on 2022-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='message',
            name='message_subject',
            field=models.CharField(default='', max_length=256, verbose_name='subject'),
            preserve_default=False,
        ),
    ]
