# Generated by Django 4.0.3 on 2022-04-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_dob_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='proficient_subjects',
        ),
    ]
