# Generated by Django 4.0.3 on 2022-04-22 08:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_remove_teacher_proficient_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='proficient_subjects',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None),
        ),
    ]
