# Generated by Django 4.0.3 on 2022-04-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('job_designation', models.CharField(max_length=256)),
                ('salary', models.IntegerField()),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StaffDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.staff')),
            ],
            options={
                'unique_together': {('staff', 'department')},
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ManyToManyField(through='staff.StaffDepartment', to='department.department'),
        ),
    ]
