# Generated by Django 4.0.3 on 2022-04-25 05:03

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
