# Generated by Django 4.0.3 on 2022-04-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('room_no', models.CharField(max_length=10)),
                ('student_count', models.PositiveSmallIntegerField()),
                ('class_teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher')),
            ],
        ),
    ]
