# Generated by Django 4.0.3 on 2022-04-04 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('subject', '0002_delete_gradesubject'),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook', models.CharField(max_length=256, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grade.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='teacher.teacher')),
            ],
            options={
                'unique_together': {('subject', 'grade')},
            },
        ),
    ]
