# Generated by Django 4.0.3 on 2022-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_dob_alter_teacher_email_and_more'),
        ('grade', '0003_alter_grade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradesubject',
            name='textbook',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('name', 'class_teacher')},
        ),
    ]
