# Generated by Django 4.0.3 on 2022-03-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_teacher_salary_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_taught',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.subject'),
        ),
    ]
