# Generated by Django 4.0.3 on 2022-03-25 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject_teacher_subject_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_taught',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
    ]
