# Generated by Django 4.0.3 on 2022-03-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_teacher_subject_taught_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='text_book',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
