# Generated by Django 4.0.3 on 2022-03-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_subject_class_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(max_length=50)),
                ('guardian_profession', models.CharField(max_length=50)),
                ('guardian_address', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=10)),
                ('enrolled_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.class')),
            ],
        ),
    ]
