# Generated by Django 4.0.3 on 2022-03-27 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_department_alter_class_name_alter_student_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'Teachers'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='short_title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RenameModel(
            old_name='Class',
            new_name='Grade',
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('A', 'Admission Fee'), ('T', 'Transportation Fee'), ('M', 'Monthly Fee'), ('S', 'Sports, ECA, and Stationery'), ('H', 'Hostel Fee'), ('O', 'Other')], max_length=1)),
                ('amount', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('full_marks', models.PositiveSmallIntegerField()),
                ('pass_marks', models.PositiveSmallIntegerField()),
                ('room_no', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
    ]
