# Generated by Django 4.0.3 on 2022-03-27 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_fee_student_exam_end_time_fee_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.grade'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.grade'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.grade'),
        ),
    ]
