# Generated by Django 4.0.3 on 2022-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_student_is_specially_abled'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_address',
            field=models.CharField(max_length=256, verbose_name="Guardian's Address"),
        ),
    ]
