# Generated by Django 4.0.3 on 2022-03-27 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_result_subject1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name': 'Fees'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='fee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='grade',
        ),
        migrations.AddField(
            model_name='fee',
            name='admission_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='monthly_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='other_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AddField(
            model_name='fee',
            name='transportation_fee',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject1_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject2_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject3_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject4_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject5_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject6_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject7_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='subject8_marks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Marks'),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='Assignments',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Departments',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='Exams',
        ),
        migrations.AlterModelTable(
            name='fee',
            table='Fees',
        ),
        migrations.AlterModelTable(
            name='grade',
            table='Classes',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='Staffs',
        ),
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='Subjects',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='Teachers',
        ),
    ]
