# Generated by Django 4.0.3 on 2022-03-29 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_subject_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='textbook',
        ),
        migrations.CreateModel(
            name='GradeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook', models.CharField(max_length=256, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.teacher')),
            ],
        ),
    ]
