# Generated by Django 4.0.3 on 2022-03-29 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_staffdepartment_teacher_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffdepartment',
            unique_together={('staff', 'department')},
        ),
    ]
