# Generated by Django 4.0.3 on 2022-04-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee', models.IntegerField(blank=True, null=True)),
                ('monthly_fee', models.IntegerField(null=True)),
                ('transportation_fee', models.IntegerField(null=True)),
                ('other_fee', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student')),
            ],
        ),
    ]
