# Generated by Django 4.0.3 on 2022-04-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(blank=True, max_length=256, null=True)),
                ('last_name', models.CharField(max_length=256)),
                ('roll_no', models.PositiveSmallIntegerField()),
                ('admission_date', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('previous_school', models.CharField(blank=True, max_length=256, null=True, verbose_name='Previous School (if any)')),
                ('guardian_name', models.CharField(max_length=256, verbose_name="Guardian's Name")),
                ('guardian_profession', models.CharField(max_length=256, verbose_name="Guardian's Profession")),
                ('guardian_address', models.CharField(max_length=256, verbose_name="Guardian's Address")),
                ('guardian_phone', models.CharField(max_length=10, verbose_name="Guardian's Phone Number")),
                ('is_specially_abled', models.BooleanField(default=False, null=True, verbose_name='Is the student specially abled?')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='grade.grade')),
            ],
        ),
    ]
