# Generated by Django 4.0.3 on 2022-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_first_name_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
