# Generated by Django 4.0.3 on 2022-04-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_alter_grade_room_no_alter_grade_student_count_and_more'),
        ('student', '0003_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('grade', 'roll_no')},
        ),
    ]
