# Generated by Django 4.0.3 on 2022-04-04 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GradeSubject',
        ),
    ]
