# Generated by Django 4.0.3 on 2022-04-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_delete_gradesubject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
