# Generated by Django 4.0.3 on 2022-04-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_alter_subject_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
