# Generated by Django 4.0.3 on 2022-04-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=256, null=True, verbose_name='Short Title')),
                ('description', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(verbose_name='Submission Due Date')),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='grade.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.subject')),
            ],
        ),
    ]
